name: bigfoot-snowboarding
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libuuid=2.41.2=he9a06e4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - python=3.14.0=h32b2ec7_102_cp314
  - python_abi=3.14=8_cp314
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - automat==25.4.16
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - constantly==23.10.4
      - cryptography==46.0.3
      - cssselect==1.3.0
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - filelock==3.20.0
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hyperframe==6.1.0
      - hyperlink==21.0.0
      - idna==3.11
      - incremental==24.7.2
      - itemadapter==0.12.2
      - itemloaders==1.3.2
      - jmespath==1.0.1
      - lxml==6.0.2
      - multidict==6.7.0
      - packaging==25.0
      - parsel==1.10.0
      - pip==25.3
      - postgrest==2.22.4
      - propcache==0.4.1
      - protego==0.5.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydispatcher==2.0.7
      - pyjwt==2.10.1
      - pyopenssl==25.3.0
      - python-dotenv==1.2.1
      - queuelib==1.8.0
      - realtime==2.22.4
      - requests==2.32.5
      - requests-file==3.0.1
      - scrapy==2.13.3
      - service-identity==24.2.0
      - setuptools==80.9.0
      - sniffio==1.3.1
      - storage3==2.22.4
      - strenum==0.4.15
      - supabase==2.22.4
      - supabase-auth==2.22.4
      - supabase-functions==2.22.4
      - tldextract==5.3.0
      - twisted==25.5.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - w3lib==2.3.1
      - websockets==15.0.1
      - yarl==1.22.0
      - zope-interface==8.0.1
prefix: /home/andyziggy/miniconda3/envs/bigfoot-snowboarding
